### ISSUE TITLE
26 / 5000 Resultados de traducción I am missing the second part 

### ISSUE THREAD

**Issue by samuel984** [Cleanshooter/simple-mail-receipt#8]
@Hi Josep thank you for sharing information.

![Booton](https://user-images.githubusercontent.com/64254514/130439961-e00e9b02-0daa-4f47-b3bc-94ec63336459.png)
 I have ready the first parte where ther server linux in gcp  receipt the mail from any account, but the second part where send mail the botton to send is disabled.

**Comment by samuel984** [comment]
I Think i am missing sevareal thinsgs.

1) In the server only is working port 25 listening I don't know that other thing I have setting to working port 443
2) . Where and how should I configure the certificate fron letsencrypt 


Can you help me please and thank you

**Comment by samuel984** [comment]
I have ready the setting api twilio sendgrind

**Comment by Cleanshooter** [comment]
If you are using AWS like I did try following an AWS tutorial for setting up let's encrypt in your ec2 instance. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html

As for why your ports aren't responding make sure they are open on the instances security group
![image](https://user-images.githubusercontent.com/2475062/134728888-856d1656-ad34-4279-bb5e-60d05925e928.png)
