### ISSUE TITLE
Don´t send for el smtp 

### ISSUE THREAD

**Issue by samuel984** [Cleanshooter/simple-mail-receipt#9]
Hi joseph this is the msj [](url)
![Resp-Twilio-server](https://user-images.githubusercontent.com/64254514/134528707-aadd00a1-983a-4051-8487-adb31175b4a9.png)

**Comment by samuel984** [comment]
Receipt mail from any cliente mail it´s ok
in flex can send the answer it´s.
The sendgrid is setting 
![setting](https://user-images.githubusercontent.com/64254514/134530134-167449e4-1374-4f52-be13-023ac8e12716.png)

**Comment by samuel984** [comment]
But I am with the problem that i Can't send the mail to coustomer end

**Comment by Cleanshooter** [comment]
I put a try/catch around the Sendgrid.js send API give that a whirl.
